import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/styles/globals.css";
import MainLayout from "@/layouts/main";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900",],
  display: "swap",
  style: ["normal"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
